name: Screenshots

on: [push, pull_request]

jobs:
  test:
    name: Lint & Test
    runs-on: macos-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --immutable

      - name: Install Browsers
        run: yarn playwright install chromium

      - name: Screenshot tests
        run: yarn test:playwright
